Link-s-Lights/grace-shopper

server/db/models/attributes.js
server/db/models/index.js
server/db/models/orderProducts.js
server/db/models/orders.js
server/db/models/productAttributes.js
server/db/models/productGroups.js
server/db/models/products.js
server/db/models/shippingAddresses.js
server/db/models/user.js
server/db/models/variation.js

database setup

---

script/seed.js
seedfiles/attributes.js
seedfiles/productAttributes.js
seedfiles/products.js
seedfiles/shippingAddresses.js
seedfiles/users.js

seed file created for products, attributes, users, addresses

---

client/components/allProducts.js
client/components/navbar.js
client/store/cart.js
client/store/index.js
client/store/products.js
client/store/singleProduct.js
client/store/user.js

Display all products

---

server/api/index.js
server/api/orders.js
server/api/products.js
server/api/products.spec.js
server/auth/index.js
server/db/models/attributes.js
server/db/models/variation.js
server/index.js

- All route scaffolding exists
- Some bugs exist on PUT routes, specifically for products

Feat: Product GET route functional, NOTE: contains bugs on some routes

---

seedfiles/productAttributes.js
seedfiles/productAttributesFunction.js

created static product attributes table

---

script/seed.js
seedfiles/products.js
server/db/models/index.js
server/db/models/products.js

seed fixed with product images

---

server/api/products.spec.js

FIX: changed testspecs to prevent blocking deployment

---

client/components/singleProduct.js

trying to fix single product

---

server/api/gatekeeper.js
server/api/orders.js
server/db/models/index.js
server/db/models/orderProducts.js
server/db/models/orders.js
server/db/models/products.js
server/db/models/user.js
server/db/models/utility.js

- changed all money values in database to INTEGERS
- added hooks to convert between pennies and dollars
- add instance functions to get subtotals for line items and orders

FEAT: made changes aligning with Ben's notes

---

client/components/allProducts.js
client/components/cart.js
client/components/navbar.js
client/components/singleProduct.js
client/components/user-home.js
client/routes.js
public/style.css

Cart button links

---

client/components/auth-form.js
client/components/cart.js
client/components/navbar.js
client/components/singleProduct.js
client/store/cart.js
client/store/user.js
client/store/user.spec.js
server/api/orders.js

can load cart upon login, saves cart to username, merges cart on login

---

client/components/navbar.js
server/api/orders.js
server/db/models/orderProducts.js
server/db/models/orders.js
server/db/models/products.js

fixed some bugs together

---

client/components/AddEditProductDetails.js
client/components/navbar.js
client/components/singleProduct.js
client/routes.js
client/store/products.js
client/store/singleProduct.js
server/api/products.js
server/api/utility.js

Add edit product

---

client/components/AddEditProductDetails.js
public/style.css

AddEditProductDetails component formatted

---

client/components/AddEditProductDetails.js
client/components/auth-form.js
client/components/navbar-login.js
client/components/navbar.js
package-lock.json
package.json
public/css/custom.css
public/css/style.css
public/index.html
scss/custom.scss

Bootstrap modifications

---

client/components/allProducts.js
client/components/cart.js
client/components/navbar.js
client/components/paginationControls.js
client/components/singleProduct.js
client/components/user-home.js
client/store/products.js
public/index.html
server/api/products.js
server/db/models/index.js
server/db/models/products.js

Product querying

---

client/components/cart.js
client/components/navbar-login.js
client/components/navbar.js
client/components/singleProduct.js
client/routes.js
client/store/cart.js
server/api/orders.js
server/auth/index.js
server/db/models/orderProducts.js
server/db/models/orders.js
server/index.js

fixed number hooks, saved address to order, need a beer now

---

client/components/index.js
server/auth/google.js
server/db/models/user.js

WE DID IT!!! google oauth!

---

client/components/Toast.js
client/components/singleProduct.js
package-lock.json
package.json
server/api/user.js

toast added for single product page

---

client/components/userForm.js
server/auth/index.js

user can edit their own address

---

client/components/Toast.js
client/components/allProducts.js

toast even a little cleaner

---

client/components/paginationControls.js

FIX: fixed pagination links

---

client/components/paginationControls.js

Best feature
